# Generated by Django 4.2 on 2023-06-20 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscribers_en',
            field=models.ManyToManyField(null=True, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers_ru',
            field=models.ManyToManyField(null=True, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='title_category_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название новости или статьи'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_category_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название новости или статьи'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_post_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_post_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='post',
            name='categories_post_en',
            field=models.ManyToManyField(null=True, through='news.PostCategory', to='news.category', verbose_name='Категория публикации'),
        ),
        migrations.AddField(
            model_name='post',
            name='categories_post_ru',
            field=models.ManyToManyField(null=True, through='news.PostCategory', to='news.category', verbose_name='Категория публикации'),
        ),
        migrations.AddField(
            model_name='post',
            name='choice_post_en',
            field=models.CharField(choices=[('СТАТЬЯ', 'Статья'), ('НОВОСТЬ', 'Новость')], max_length=7, null=True, verbose_name='Выбор публикации'),
        ),
        migrations.AddField(
            model_name='post',
            name='choice_post_ru',
            field=models.CharField(choices=[('СТАТЬЯ', 'Статья'), ('НОВОСТЬ', 'Новость')], max_length=7, null=True, verbose_name='Выбор публикации'),
        ),
        migrations.AddField(
            model_name='post',
            name='date_post_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='post',
            name='date_post_ru',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='post',
            name='rating_post_en',
            field=models.IntegerField(default=0, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='post',
            name='rating_post_ru',
            field=models.IntegerField(default=0, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_post_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_post_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_post_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_post_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories_post',
            field=models.ManyToManyField(through='news.PostCategory', to='news.category', verbose_name='Категория публикации'),
        ),
        migrations.CreateModel(
            name='PostCategory_ru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='Категория')),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Категория публикации [ru]',
                'verbose_name_plural': 'Категории публикаций [ru]',
                'db_table': 'news_postcategory_ru',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
        migrations.CreateModel(
            name='PostCategory_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='Категория')),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Категория публикации [en]',
                'verbose_name_plural': 'Категории публикаций [en]',
                'db_table': 'news_postcategory_en',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
    ]
