# Generated by Django 4.2 on 2023-06-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_subscribers_en_category_subscribers_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory_ru',
            name='category_post',
        ),
        migrations.RemoveField(
            model_name='postcategory_ru',
            name='post_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subscribers_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subscribers_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_post_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_post_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories_post_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories_post_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='choice_post_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='choice_post_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_post_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_post_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating_post_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating_post_ru',
        ),
        migrations.DeleteModel(
            name='PostCategory_en',
        ),
        migrations.DeleteModel(
            name='PostCategory_ru',
        ),
    ]
