# Generated by Django 4.2 on 2023-07-12 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Координата',
                'verbose_name_plural': 'Координаты',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(blank=True, max_length=255, verbose_name='Заголовок фото 1')),
                ('image_1', models.ImageField(blank=True, upload_to='media/pereval/%Y/%m/%d', verbose_name='Фотография 1')),
                ('title_2', models.CharField(blank=True, max_length=255, verbose_name='Заголовок фото 2')),
                ('image_2', models.ImageField(blank=True, upload_to='media/pereval/%Y/%m/%d', verbose_name='Фотография 2')),
                ('title_3', models.CharField(blank=True, max_length=255, verbose_name='Заголовок фото 3')),
                ('image_3', models.ImageField(blank=True, upload_to='media/pereval/%Y/%m/%d', verbose_name='Фотография 3')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=255, verbose_name='Префикс')),
                ('title', models.CharField(max_length=255, verbose_name='Название перевала')),
                ('other_titles', models.CharField(max_length=255, verbose_name='Другое название')),
                ('connect', models.CharField(max_length=255, verbose_name='Соединяет')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending', 'Модератор взял в работу'), ('accepted', 'Модерация прошла успешно'), ('rejected', 'Модерация прошла, информация не принята')], default='new', max_length=8, verbose_name='Статус данных')),
                ('level', models.CharField(choices=[('winter-1A', 'Зима-1А'), ('winter-2A', 'Зима-2А'), ('winter-3A', 'Зима-3А'), ('winter-1B', 'Зима-1Б'), ('winter-2B', 'Зима-2Б'), ('winter-3B', 'Зима-3Б'), ('spring-1A', 'Весна-1А'), ('spring-2A', 'Весна-2А'), ('spring-3A', 'Весна-3А'), ('spring-1B', 'Весна-1Б'), ('spring-2B', 'Весна-2Б'), ('spring-3B', 'Весна-3Б'), ('summer-1A', 'Лето-1А'), ('summer-2A', 'Лето-2А'), ('summer-3A', 'Лето-3А'), ('summer-1B', 'Лето-1Б'), ('summer-2B', 'Лето-2Б'), ('summer-3B', 'Лето-3Б'), ('autumn-1A', 'Осень-1А'), ('autumn-2A', 'Осень-2А'), ('autumn-3A', 'Осень-3А'), ('autumn-1B', 'Осень-1Б'), ('autumn-2B', 'Осень-2Б'), ('autumn-3B', 'Осень-3Б')], max_length=9, verbose_name='Категория трудности')),
            ],
            options={
                'verbose_name': 'Перевал',
                'verbose_name_plural': 'Перевалы',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('surname', models.CharField(max_length=20, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=20, verbose_name='Электронная почта')),
                ('phone', models.CharField(help_text='input format: "+70123456789"', max_length=12, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
        migrations.AddField(
            model_name='pereval',
            name='coordinates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.coords', verbose_name='Координаты'),
        ),
        migrations.AddField(
            model_name='pereval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.users', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='images',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.pereval'),
        ),
    ]
