# Generated by Django 5.0.6 on 2024-11-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('weekdays', models.CharField(max_length=100, verbose_name='ПН-ПТ')),
                ('weekends', models.CharField(max_length=255, verbose_name='СБ, ВС')),
                ('phone', models.CharField(max_length=49, verbose_name='Телефон')),
                ('email', models.CharField(max_length=60, verbose_name='E-mail')),
                ('instagram', models.CharField(max_length=100, verbose_name='Instagram')),
                ('vk', models.CharField(max_length=100, verbose_name='VK')),
                ('photo_1', models.ImageField(upload_to='photos/contact/', verbose_name='Фотография 1')),
                ('photo_2', models.ImageField(upload_to='photos/contact/', verbose_name='Фотография 2')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
