# Generated by Django 4.2 on 2023-06-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
