# Generated by Django 4.2 on 2023-07-31 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя мастера')),
                ('avatar', models.ImageField(blank=True, upload_to='', verbose_name='Фотография мастера')),
                ('info', models.TextField(blank=True, verbose_name='Описание работ мастера')),
                ('portfolio', models.URLField(blank=True, verbose_name='Фотографии работ')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название салона')),
                ('info', models.TextField(blank=True, verbose_name='О салоне')),
                ('time', models.CharField(blank=True, help_text='БЕЗ ВЫХОДНЫХ с 10:00 до 22:00', max_length=255, verbose_name='Часы работы')),
                ('address', models.TextField(blank=True, max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, help_text='Формат ввода: +70123456789', max_length=12, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=30, verbose_name='Электронная почта')),
                ('web', models.CharField(blank=True, max_length=255, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название услуги')),
                ('text', models.TextField(blank=True, verbose_name='Описание услуги')),
                ('services', models.CharField(choices=[('nails', 'Ногти'), ('eyelashes', 'Ресницы')], default='nails', max_length=9, verbose_name='Выбор услуги')),
                ('price', models.FloatField(default=0.0, null=True, verbose_name='Стоимость услуги')),
                ('salon', models.ManyToManyField(to='salon.salon', verbose_name='Выбор салона')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(help_text='Формат ввода: +70123456789', max_length=12, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=30, verbose_name='Электронная почта')),
                ('date', models.DateTimeField(verbose_name='Дата и время записи')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.master', verbose_name='Выбор мастера')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.salon', verbose_name='Выбор салона для записи')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.services', verbose_name='Выбор услуги')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.AddField(
            model_name='master',
            name='salon',
            field=models.ManyToManyField(to='salon.salon', verbose_name='Салон мастера'),
        ),
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(to='salon.services', verbose_name='Услуги мастера'),
        ),
    ]
